[package]
name = "blog-dns-d"
version = "0.1.0"
authors = ["Dave Minter <dave@paperstack.com>"]
edition = "2018"
description = "Daemon for micro-blogging via DNS TXT records"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
zerocopy = { version = "0.7.34", features = ["derive"] }
chrono = "0.4.38"
clap = { version = "4.5.15", features = ["derive"] }
log = "0.4.22"
env_logger = "0.11.5"