[package]
name = "blog-dns-d"
version = "0.1.0"
authors = ["Dave Minter <dave@paperstack.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitlab = "1.1.0"
byteorder = "1.4.3"